version: '3.7'
services:
  blog:
    image: kkrepo/blog:v1.1
    ports:
      - "8080:8080"
    volumes:
      - /opt/blog/logs:/opt/blog/logs:rw
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
